version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
    - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: go
      MYSQL_PASSWORD: go
